version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - pg:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: perebevaska/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app_backend/static/
      - media_value:/app_backend/media/
    depends_on:
      - db
    env_file:
      - ./.env


  frontend:
    build: ../frontend
    volumes:
      - frontend:/app/result_build/


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    restart: always

volumes:
  pg:
  static_value:
  media_value:
  frontend:


