# Generated by Django 4.2 on 2023-05-01 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0003_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient',
        ),
    ]
