# Generated by Django 4.2 on 2023-05-01 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_remove_ingredient_unique_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measure_unit',
            new_name='measurement_unit',
        ),
    ]
