# Generated by Django 4.2 on 2023-05-05 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0005_rename_measure_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',)},
        ),
    ]
